version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-cli-eslint
    versions:
    - "> 4.2.2"
  - dependency-name: ember-cli
    versions:
    - 3.24.0
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
